#! /usr/local/bin/python3.7

verbose = '''

    Clean Python cache 0.4

'''

__name__ == "__main__"

from gcode.primitive import rm
from gcode.unit.system import Mapper


DIR_TARGET = ['__pycache__', '.egg-info',]


class Cleaner(Mapper):
    def clean(self):
        for pdir, dir in self.dirs:
            for DIR in DIR_TARGET:
                if DIR in dir:
                    rm(pdir)
                    self.Log(f'Deleted {pdir}', True)


c = Cleaner()

c.clean()
