#! /usr/local/bin/python3.7

__name__ == "__main__"

from gcode.primitive.filesystem import pwd, rm
from gcode.primitive.walker import Walker
from gcode.primitive.style import LOG

DIR_TARGET = ['__pycache__', '.egg-info',]

w = Walker(pwd())

w.start()

for pdir, dir in w.dirs.items():
    for DIR in DIR_TARGET:
        if DIR in dir:
            print(pdir,LOG(True))
            rm(pdir)

w = None
